name: Barbershop App CI/CD

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.4'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Type check
        run: npm run tsc

      - name: Run tests
        run: npm test

  build-android:
    name: Build Android App
    needs: lint-and-test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo and EAS
        run: npm install -g expo-cli eas-cli

      - name: Authenticate with Expo
        run: echo "${{ secrets.EXPO_TOKEN }}" | expo login

      - name: Build Android preview
        run: eas build --platform android --profile preview --non-interactive

  build-ios:
    name: Build iOS App
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo and EAS
        run: npm install -g expo-cli eas-cli

      - name: Authenticate with Expo
        run: echo "${{ secrets.EXPO_TOKEN }}" | expo login

      - name: Build iOS preview
        run: eas build --platform ios --profile preview --non-interactive