name: Expo EAS CI/CD

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (אופציונלי)
      - name: Run tests
        run: npm test || echo "No tests found"

      # Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Build for Android & iOS
      - name: Build with EAS
        run: eas build --platform all --non-interactive --profile production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  submit:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Submit to App Store & Google Play
      - name: Submit builds
        run: eas submit --platform all --non-interactive --latest
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          APP_STORE_CONNECT_API_KEY_PATH: ${{ secrets.APP_STORE_CONNECT_API_KEY_PATH }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
